# Write Kubernetes Deployment Script

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722-part2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8801
        env:
        - name: PORT
          value: "8801"
        - name: DATABASE_URL
          value: "postgresql://sit722_part2_35sy_user:10QMQKzDbVvnfb7mnqlQVwiuzjRgUraR@dpg-cr83i8rqf0us73bom2pg-a.oregon-postgres.render.com/sit722_part2_35sy"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8801
      targetPort: 8801
      nodePort: 30001